public class PoemWords {

    public static String[] words = {
        "whisper", "eternity", "dream", "silent", "ocean", "shadow", "light", "heart", "breeze", "sky",
        "moon", "star", "river", "flow", "mountain", "valley", "rain", "sunrise", "sunset", "dawn", 
        "twilight", "night", "day", "bird", "wing", "feather", "flight", "tree", "branch", "leaf", 
        "flower", "bloom", "rose", "thorn", "earth", "wind", "fire", "water", "stone", "dust", "sand", 
        "shore", "wave", "tide", "current", "storm", "cloud", "mist", "fog", "dew", "raindrop", 
        "drizzle", "snow", "ice", "frost", "cold", "heat", "flame", "glow", "spark", "ember", "ash", 
        "burn", "ignite", "smoke", "whirl", "whisper", "echo", "sigh", "breath", "voice", "sound", 
        "melody", "song", "harmony", "tune", "rhythm", "beat", "pulse", "silence", "quiet", "still", 
        "calm", "peace", "chaos", "storm", "wild", "free", "bound", "chain", "lock", "key", "door", 
        "path", "road", "journey", "travel", "wander", "explore", "adventure", "discover", "mystery", 
        "secret", "hidden", "veiled", "truth", "lie", "mask", "illusion", "dream", "nightmare", "hope", 
        "despair", "joy", "sorrow", "grief", "tears", "smile", "laugh", "cry", "fear", "brave", "courage", 
        "strength", "weakness", "fragile", "broken", "whole", "heal", "mend", "love", "hate", "desire", 
        "longing", "yearn", "passion", "fire", "burn", "kiss", "embrace", "touch", "hold", "release", 
        "let go", "freedom", "bond", "connection", "distance", "apart", "together", "alone", "lonely", 
        "friend", "stranger", "soul", "spirit", "body", "mind", "heart", "life", "death", "beginning", 
        "end", "infinity", "time", "eternity", "moment", "past", "present", "future", "memory", "forgotten", 
        "lost", "found", "search", "seek", "wander", "roam", "return", "stay", "leave", "goodbye", "hello", 
        "greeting", "farewell", "welcome", "departure", "arrival", "home", "journey", "destination", "map", 
        "compass", "guide", "follow", "lead", "trail", "sign", "signal", "light", "dark", "shadow", "bright", 
        "glimmer", "shine", "sparkle", "glisten", "glow", "radiate", "reflect", "mirror", "image", "picture", 
        "vision", "dream", "reality", "illusion", "fantasy", "truth", "lie", "fiction", "story", "tale", 
        "legend", "myth", "history", "future", "past", "present", "today", "tomorrow", "yesterday", "forever", 
        "always", "never", "sometimes", "often", "rarely", "occasionally", "frequently", "once", "twice", 
        "again", "nevermore", "evermore", "soon", "later", "now", "then", "before", "after", "eternity", 
        "infinity", "endless", "timeless", "age", "century", "decade", "year", "month", "week", "day", 
        "hour", "minute", "second", "moment", "instant", "pause", "halt", "stop", "start", "begin", "end", 
        "finish", "complete", "incomplete", "continue", "persist", "endure", "survive", "exist", "fade", 
        "vanish", "disappear", "appear", "arrive", "depart", "return", "leave", "escape", "flee", "run", 
        "chase", "pursue", "catch", "grab", "hold", "release", "drop", "fall", "rise", "stand", "sit", 
        "walk", "run", "fly", "soar", "jump", "leap", "dance", "spin", "twirl", "turn", "circle", "round", 
        "square", "shape", "form", "figure", "pattern", "design", "create", "build", "destroy", "ruin", 
        "wreck", "shatter", "break", "mend", "fix", "heal", "repair", "restore", "reborn", "regrow", "revive", 
        "refresh", "renew", "rebuild", "remake", "remodel", "reshape", "reform", "transform", "change", 
        "shift", "move", "still", "motion", "pause", "stop", "halt", "start", "continue", "persist", 
        "endure", "survive", "thrive", "live", "die", "exist", "fade", "disappear", "vanish", "return", 
        "come back", "depart", "arrive", "leave", "go", "stay", "remain", "linger", "wait", "hurry", "rush", 
        "slow", "quick", "fast", "swift", "speed", "pace", "tempo", "beat", "rhythm", "tune", "melody", 
        "song", "music", "sound", "noise", "echo", "voice", "whisper", "speak", "talk", "shout", "yell", 
        "cry", "laugh", "smile", "grin", "frown", "scowl", "glare", "stare", "look", "see", "watch", 
        "observe", "gaze", "glimpse", "peer", "view", "sight", "vision", "dream", "image", "picture", 
        "scene", "landscape", "horizon", "view", "outlook", "perspective", "angle", "point", "aspect"
    };
    
}
